//
//  CardsLoader.m
//  Cards Against Humanity
//
//  Created by bancarel valentin on 03/07/15.
//  Copyright (c) 2015 bancarel valentin. All rights reserved.
//

#import "HardLoader.h"

@implementation HardLoader

+(NSArray*)getBlackCards{
    NSArray* blackCards = [[NSMutableArray alloc]initWithObjects:
                          [[BlackCard alloc]initFromText:@"A Gypsy curse."],
[[BlackCard alloc]initFromText:@"A moment of silence."],
[[BlackCard alloc]initFromText:@"A sausage festival."],
[[BlackCard alloc]initFromText:@"An honest cop with nothing left to lose."],
[[BlackCard alloc]initFromText:@"Famine."],
[[BlackCard alloc]initFromText:@"Flesh-eating bacteria."],
[[BlackCard alloc]initFromText:@"Flying sex snakes."],
[[BlackCard alloc]initFromText:@"Not giving a shit about the Third World."],
[[BlackCard alloc]initFromText:@"Sexting."],
[[BlackCard alloc]initFromText:@"Shapeshifters."],
[[BlackCard alloc]initFromText:@"Porn stars."],
[[BlackCard alloc]initFromText:@"72 virgins."],
[[BlackCard alloc]initFromText:@"A drive-by shooting."],
[[BlackCard alloc]initFromText:@"A time travel paradox."],
[[BlackCard alloc]initFromText:@"Authentic Mexican cuisine."],
[[BlackCard alloc]initFromText:@"Bling."],
[[BlackCard alloc]initFromText:@"Consultants."],
[[BlackCard alloc]initFromText:@"Crippling debt."],
[[BlackCard alloc]initFromText:@"Daddy issues."],
[[BlackCard alloc]initFromText:@"The Donald Trump Seal of Approval™."],
[[BlackCard alloc]initFromText:@"Dropping a chandelier on your enemies and riding the rope up."],
[[BlackCard alloc]initFromText:@"Former President George W. Bush."],
[[BlackCard alloc]initFromText:@"Full frontal nudity."],
[[BlackCard alloc]initFromText:@"Hormone injections."],
[[BlackCard alloc]initFromText:@"Laying an egg."],
[[BlackCard alloc]initFromText:@"Getting naked and watching Nickelodeon."],
[[BlackCard alloc]initFromText:@"Pretending to care."],
[[BlackCard alloc]initFromText:@"Public ridicule."],
[[BlackCard alloc]initFromText:@"Sharing needles."],
[[BlackCard alloc]initFromText:@"Boogers."],
[[BlackCard alloc]initFromText:@"The inevitable heat death of the universe."],
[[BlackCard alloc]initFromText:@"The miracle of childbirth."],
[[BlackCard alloc]initFromText:@"The Rapture."],
[[BlackCard alloc]initFromText:@"Whipping it out."],
[[BlackCard alloc]initFromText:@"White privilege."],
[[BlackCard alloc]initFromText:@"Wifely duties."],
[[BlackCard alloc]initFromText:@"The Hamburglar."],
[[BlackCard alloc]initFromText:@"AXE Body Spray."],
[[BlackCard alloc]initFromText:@"The Blood of Christ."],
[[BlackCard alloc]initFromText:@"Horrifying laser hair removal accidents."],
[[BlackCard alloc]initFromText:@"BATMAN!!!"],
[[BlackCard alloc]initFromText:@"Agriculture."],
[[BlackCard alloc]initFromText:@"A robust mongoloid."],
[[BlackCard alloc]initFromText:@"Natural selection."],
[[BlackCard alloc]initFromText:@"Coat hanger abortions."],
[[BlackCard alloc]initFromText:@"Eating all of the cookies before the AIDS bake-sale."],
[[BlackCard alloc]initFromText:@"Michelle Obama's arms."],
[[BlackCard alloc]initFromText:@"The World of Warcraft."],
[[BlackCard alloc]initFromText:@"Swooping."],
[[BlackCard alloc]initFromText:@"Obesity."],
[[BlackCard alloc]initFromText:@"A homoerotic volleyball montage."],
[[BlackCard alloc]initFromText:@"Lockjaw."],
[[BlackCard alloc]initFromText:@"A mating display."],
[[BlackCard alloc]initFromText:@"Testicular torsion."],
[[BlackCard alloc]initFromText:@"All-you-can-eat shrimp for $4.99."],
[[BlackCard alloc]initFromText:@"Domino's™ Oreo™ Dessert Pizza."],
[[BlackCard alloc]initFromText:@"Kanye West."],
[[BlackCard alloc]initFromText:@"Hot cheese."],
[[BlackCard alloc]initFromText:@"Raptor attacks."],
[[BlackCard alloc]initFromText:@"Taking off your shirt."],
[[BlackCard alloc]initFromText:@"Smegma."],
[[BlackCard alloc]initFromText:@"Alcoholism."],
[[BlackCard alloc]initFromText:@"A middle-aged man on roller skates."],
[[BlackCard alloc]initFromText:@"The Care Bear Stare."],
[[BlackCard alloc]initFromText:@"Bingeing and purging."],
[[BlackCard alloc]initFromText:@"Oversized lollipops."],
[[BlackCard alloc]initFromText:@"Self-loathing."],
[[BlackCard alloc]initFromText:@"Children on leashes."],
[[BlackCard alloc]initFromText:@"Half-assed foreplay."],
[[BlackCard alloc]initFromText:@"The Holy Bible."],
[[BlackCard alloc]initFromText:@"German dungeon porn."],
[[BlackCard alloc]initFromText:@"Being on fire."],
[[BlackCard alloc]initFromText:@"Teenage pregnancy."],
[[BlackCard alloc]initFromText:@"Gandhi."],
[[BlackCard alloc]initFromText:@"Leaving an awkward voicemail."],
[[BlackCard alloc]initFromText:@"Uppercuts."],
[[BlackCard alloc]initFromText:@"Customer service representatives."],
[[BlackCard alloc]initFromText:@"An erection that lasts longer than four hours."],
[[BlackCard alloc]initFromText:@"My genitals."],
[[BlackCard alloc]initFromText:@"Picking up girls at the abortion clinic."],
[[BlackCard alloc]initFromText:@"Science."],
[[BlackCard alloc]initFromText:@"Not reciprocating oral sex."],
[[BlackCard alloc]initFromText:@"Flightless birds."],
[[BlackCard alloc]initFromText:@"A good sniff."],
[[BlackCard alloc]initFromText:@"Waterboarding."],
[[BlackCard alloc]initFromText:@"A balanced breakfast."],
[[BlackCard alloc]initFromText:@"Historically black colleges."],
[[BlackCard alloc]initFromText:@"Actually taking candy from a baby."],
[[BlackCard alloc]initFromText:@"The Make-A-Wish Foundation."],
[[BlackCard alloc]initFromText:@"A clandestine butt scratch."],
[[BlackCard alloc]initFromText:@"Passive-aggressive Post-it notes."],
[[BlackCard alloc]initFromText:@"The Chinese gymnastics team."],
[[BlackCard alloc]initFromText:@"Switching to Geico."],
[[BlackCard alloc]initFromText:@"Peeing a little bit."],
[[BlackCard alloc]initFromText:@"Home video of Oprah sobbing into a Lean Cuisine."],
[[BlackCard alloc]initFromText:@"Nocturnal emissions."],
[[BlackCard alloc]initFromText:@"The Jews."],
[[BlackCard alloc]initFromText:@"My humps."],
[[BlackCard alloc]initFromText:@"Powerful thighs."],
[[BlackCard alloc]initFromText:@"Winking at old people."],
[[BlackCard alloc]initFromText:@"Mr. Clean, right behind you."],
[[BlackCard alloc]initFromText:@"A gentle caress of the inner thigh."],
[[BlackCard alloc]initFromText:@"Sexual tension."],
[[BlackCard alloc]initFromText:@"The forbidden fruit."],
[[BlackCard alloc]initFromText:@"Skeletor."],
[[BlackCard alloc]initFromText:@"Fancy Feast."],
[[BlackCard alloc]initFromText:@"Being rich."],
[[BlackCard alloc]initFromText:@"Sweet, sweet vengeance."],
[[BlackCard alloc]initFromText:@"Republicans."],
[[BlackCard alloc]initFromText:@"A gassy antelope."],
[[BlackCard alloc]initFromText:@"Natalie Portman."],
[[BlackCard alloc]initFromText:@"Copping a feel."],
[[BlackCard alloc]initFromText:@"Kamikaze pilots."],
[[BlackCard alloc]initFromText:@"Sean Connery."],
[[BlackCard alloc]initFromText:@"The homosexual agenda."],
[[BlackCard alloc]initFromText:@"The hardworking Mexican."],
[[BlackCard alloc]initFromText:@"A falcon with a cap on its head."],
[[BlackCard alloc]initFromText:@"Altar boys."],
[[BlackCard alloc]initFromText:@"The Kool-Aid Man."],
[[BlackCard alloc]initFromText:@"Getting so angry that you pop a boner."],
[[BlackCard alloc]initFromText:@"Free samples."],
[[BlackCard alloc]initFromText:@"A big hoopla about nothing."],
[[BlackCard alloc]initFromText:@"Doing the right thing."],
[[BlackCard alloc]initFromText:@"The Three-Fifths compromise."],
[[BlackCard alloc]initFromText:@"Lactation."],
[[BlackCard alloc]initFromText:@"World peace."],
[[BlackCard alloc]initFromText:@"RoboCop."],
[[BlackCard alloc]initFromText:@"Chutzpah."],
[[BlackCard alloc]initFromText:@"Justin Bieber."],
[[BlackCard alloc]initFromText:@"Oompa-Loompas."],
[[BlackCard alloc]initFromText:@"Inappropriate yodeling."],
[[BlackCard alloc]initFromText:@"Puberty."],
[[BlackCard alloc]initFromText:@"Ghosts."],
[[BlackCard alloc]initFromText:@"An asymmetric boob job."],
[[BlackCard alloc]initFromText:@"Vigorous jazz hands."],
[[BlackCard alloc]initFromText:@"Fingering."],
[[BlackCard alloc]initFromText:@"Glenn Beck catching his scrotum on a curtain hook."],
[[BlackCard alloc]initFromText:@"GoGurt."],
[[BlackCard alloc]initFromText:@"Police brutality."],
[[BlackCard alloc]initFromText:@"John Wilkes Booth."],
[[BlackCard alloc]initFromText:@"Preteens."],
[[BlackCard alloc]initFromText:@"Scalping."],
[[BlackCard alloc]initFromText:@"Stifling a giggle at the mention of Hutus and Tutsis."],
[[BlackCard alloc]initFromText:@"\"Tweeting.\""],
[[BlackCard alloc]initFromText:@"Darth Vader."],
[[BlackCard alloc]initFromText:@"A sad handjob."],
[[BlackCard alloc]initFromText:@"Exactly what you'd expect."],
[[BlackCard alloc]initFromText:@"Expecting a burp and vomiting on the floor."],
[[BlackCard alloc]initFromText:@"Adderall™."],
[[BlackCard alloc]initFromText:@"Embryonic stem cells."],
[[BlackCard alloc]initFromText:@"Tasteful sideboob."],
[[BlackCard alloc]initFromText:@"Panda sex."],
[[BlackCard alloc]initFromText:@"An icepick lobotomy."],
[[BlackCard alloc]initFromText:@"Tom Cruise."],
[[BlackCard alloc]initFromText:@"Mouth herpes."],
[[BlackCard alloc]initFromText:@"Sperm whales."],
[[BlackCard alloc]initFromText:@"Homeless people."],
[[BlackCard alloc]initFromText:@"Third base."],
[[BlackCard alloc]initFromText:@"Incest."],
[[BlackCard alloc]initFromText:@"Pac-Man uncontrollably guzzling cum."],
[[BlackCard alloc]initFromText:@"A mime having a stroke."],
[[BlackCard alloc]initFromText:@"Hulk Hogan."],
[[BlackCard alloc]initFromText:@"God."],
[[BlackCard alloc]initFromText:@"Scrubbing under the folds."],
[[BlackCard alloc]initFromText:@"Golden showers."],
[[BlackCard alloc]initFromText:@"Emotions."],
[[BlackCard alloc]initFromText:@"Licking things to claim them as your own."],
[[BlackCard alloc]initFromText:@"Pabst Blue Ribbon."],
[[BlackCard alloc]initFromText:@"The placenta."],
[[BlackCard alloc]initFromText:@"Spontaneous human combustion."],
[[BlackCard alloc]initFromText:@"Friends with benefits."],
[[BlackCard alloc]initFromText:@"Finger painting."],
[[BlackCard alloc]initFromText:@"Old-people smell."],
[[BlackCard alloc]initFromText:@"Dying of dysentery."],
[[BlackCard alloc]initFromText:@"My inner demons."],
[[BlackCard alloc]initFromText:@"A Super Soaker™ full of cat pee."],
[[BlackCard alloc]initFromText:@"Aaron Burr."],
[[BlackCard alloc]initFromText:@"Cuddling."],
[[BlackCard alloc]initFromText:@"The chronic."],
[[BlackCard alloc]initFromText:@"Cockfights."],
[[BlackCard alloc]initFromText:@"Friendly fire."],
[[BlackCard alloc]initFromText:@"Ronald Reagan."],
[[BlackCard alloc]initFromText:@"A disappointing birthday party."],
[[BlackCard alloc]initFromText:@"A sassy black woman."],
[[BlackCard alloc]initFromText:@"Mathletes."],
[[BlackCard alloc]initFromText:@"A tiny horse."],
[[BlackCard alloc]initFromText:@"William Shatner."],
[[BlackCard alloc]initFromText:@"Riding off into the sunset."],
[[BlackCard alloc]initFromText:@"An M. Night Shyamalan plot twist."],
[[BlackCard alloc]initFromText:@"Jew-fros."],
[[BlackCard alloc]initFromText:@"Mutually-assured destruction."],
[[BlackCard alloc]initFromText:@"Pedophiles."],
[[BlackCard alloc]initFromText:@"Yeast."],
[[BlackCard alloc]initFromText:@"Grave robbing."],
[[BlackCard alloc]initFromText:@"Eating the last known bison."],
[[BlackCard alloc]initFromText:@"Catapults."],
[[BlackCard alloc]initFromText:@"Poor people."],
[[BlackCard alloc]initFromText:@"Forgetting the Alamo."],
[[BlackCard alloc]initFromText:@"The Hustle."],
[[BlackCard alloc]initFromText:@"The Force."],
[[BlackCard alloc]initFromText:@"Wiping her butt."],
[[BlackCard alloc]initFromText:@"Intelligent design."],
[[BlackCard alloc]initFromText:@"Loose lips."],
[[BlackCard alloc]initFromText:@"AIDS."],
[[BlackCard alloc]initFromText:@"Pictures of boobs."],
[[BlackCard alloc]initFromText:@"The Übermensch."],
[[BlackCard alloc]initFromText:@"Sarah Palin."],
[[BlackCard alloc]initFromText:@"American Gladiators."],
[[BlackCard alloc]initFromText:@"Getting really high."],
[[BlackCard alloc]initFromText:@"Scientology."],
[[BlackCard alloc]initFromText:@"Penis envy."],
[[BlackCard alloc]initFromText:@"Praying the gay away."],
[[BlackCard alloc]initFromText:@"Frolicking."],
[[BlackCard alloc]initFromText:@"Two midgets shitting into a bucket."],
[[BlackCard alloc]initFromText:@"The KKK."],
[[BlackCard alloc]initFromText:@"Genghis Khan."],
[[BlackCard alloc]initFromText:@"Crystal meth."],
[[BlackCard alloc]initFromText:@"Serfdom."],
[[BlackCard alloc]initFromText:@"Stranger danger."],
[[BlackCard alloc]initFromText:@"A Bop It™."],
[[BlackCard alloc]initFromText:@"Shaquille O'Neal's acting career."],
[[BlackCard alloc]initFromText:@"Prancing."],
[[BlackCard alloc]initFromText:@"Vigilante justice."],
[[BlackCard alloc]initFromText:@"Overcompensation."],
[[BlackCard alloc]initFromText:@"Pixelated bukkake."],
[[BlackCard alloc]initFromText:@"A lifetime of sadness."],
[[BlackCard alloc]initFromText:@"Racism."],
[[BlackCard alloc]initFromText:@"Dwarf tossing."],
[[BlackCard alloc]initFromText:@"Sunshine and rainbows."],
[[BlackCard alloc]initFromText:@"A monkey smoking a cigar."],
[[BlackCard alloc]initFromText:@"Flash flooding."],
[[BlackCard alloc]initFromText:@"Lance Armstrong's missing testicle."],
[[BlackCard alloc]initFromText:@"Dry heaving."],
[[BlackCard alloc]initFromText:@"The terrorists."],
[[BlackCard alloc]initFromText:@"Britney Spears at 55."],
[[BlackCard alloc]initFromText:@"Attitude."],
[[BlackCard alloc]initFromText:@"Breaking out into song and dance."],
[[BlackCard alloc]initFromText:@"Leprosy."],
[[BlackCard alloc]initFromText:@"Gloryholes."],
[[BlackCard alloc]initFromText:@"Nipple blades."],
[[BlackCard alloc]initFromText:@"The heart of a child."],
[[BlackCard alloc]initFromText:@"Puppies!"],
[[BlackCard alloc]initFromText:@"Waking up half-naked in a Denny's parking lot."],
[[BlackCard alloc]initFromText:@"Dental dams."],
[[BlackCard alloc]initFromText:@"Toni Morrison's vagina."],
[[BlackCard alloc]initFromText:@"The taint; the grundle; the fleshy fun-bridge."],
[[BlackCard alloc]initFromText:@"Active listening."],
[[BlackCard alloc]initFromText:@"Ethnic cleansing."],
[[BlackCard alloc]initFromText:@"The Little Engine That Could."],
[[BlackCard alloc]initFromText:@"The invisible hand."],
[[BlackCard alloc]initFromText:@"Waiting ‘til marriage."],
[[BlackCard alloc]initFromText:@"Unfathomable stupidity."],
[[BlackCard alloc]initFromText:@"Euphoria™ by Calvin Klein."],
[[BlackCard alloc]initFromText:@"Re-gifting."],
[[BlackCard alloc]initFromText:@"Autocannibalism."],
[[BlackCard alloc]initFromText:@"Erectile dysfunction."],
[[BlackCard alloc]initFromText:@"My collection of high-tech sex toys."],
[[BlackCard alloc]initFromText:@"The Pope."],
[[BlackCard alloc]initFromText:@"White people."],
[[BlackCard alloc]initFromText:@"Tentacle porn."],
[[BlackCard alloc]initFromText:@"Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts."],
[[BlackCard alloc]initFromText:@"Too much hair gel."],
[[BlackCard alloc]initFromText:@"Seppuku."],
[[BlackCard alloc]initFromText:@"Same-sex ice dancing."],
[[BlackCard alloc]initFromText:@"Cheating in the Special Olympics."],
[[BlackCard alloc]initFromText:@"Charisma."],
[[BlackCard alloc]initFromText:@"Keanu Reeves."],
[[BlackCard alloc]initFromText:@"Sean Penn."],
[[BlackCard alloc]initFromText:@"Nickelback."],
[[BlackCard alloc]initFromText:@"A look-see."],
[[BlackCard alloc]initFromText:@"Pooping back and forth. Forever."],
[[BlackCard alloc]initFromText:@"Menstruation."],
[[BlackCard alloc]initFromText:@"Kids with ass cancer."],
[[BlackCard alloc]initFromText:@"A salty surprise."],
[[BlackCard alloc]initFromText:@"The South."],
[[BlackCard alloc]initFromText:@"The violation of our most basic human rights."],
[[BlackCard alloc]initFromText:@"YOU MUST CONSTRUCT ADDITIONAL PYLONS."],
[[BlackCard alloc]initFromText:@"Being fabulous."],
[[BlackCard alloc]initFromText:@"Necrophilia."],
[[BlackCard alloc]initFromText:@"Centaurs."],
[[BlackCard alloc]initFromText:@"Bill Nye the Science Guy."],
[[BlackCard alloc]initFromText:@"Black people."],
[[BlackCard alloc]initFromText:@"Chivalry."],
[[BlackCard alloc]initFromText:@"Lunchables™."],
[[BlackCard alloc]initFromText:@"Bitches."],
[[BlackCard alloc]initFromText:@"The profoundly handicapped."],
[[BlackCard alloc]initFromText:@"Heartwarming orphans."],
[[BlackCard alloc]initFromText:@"MechaHitler."],
[[BlackCard alloc]initFromText:@"Fiery poops."],
[[BlackCard alloc]initFromText:@"Another goddamn vampire movie."],
[[BlackCard alloc]initFromText:@"Tangled Slinkys."],
[[BlackCard alloc]initFromText:@"The true meaning of Christmas."],
[[BlackCard alloc]initFromText:@"Estrogen."],
[[BlackCard alloc]initFromText:@"A zesty breakfast burrito."],
[[BlackCard alloc]initFromText:@"That thing that electrocutes your abs."],
[[BlackCard alloc]initFromText:@"Passing a kidney stone."],
[[BlackCard alloc]initFromText:@"A bleached asshole."],
[[BlackCard alloc]initFromText:@"Michael Jackson."],
[[BlackCard alloc]initFromText:@"Cybernetic enhancements."],
[[BlackCard alloc]initFromText:@"Guys who don't call."],
[[BlackCard alloc]initFromText:@"Smallpox blankets."],
[[BlackCard alloc]initFromText:@"Masturbation."],
[[BlackCard alloc]initFromText:@"Classist undertones."],
[[BlackCard alloc]initFromText:@"Queefing."],
[[BlackCard alloc]initFromText:@"Concealing a boner."],
[[BlackCard alloc]initFromText:@"Edible underpants."],
[[BlackCard alloc]initFromText:@"Viagra."],
[[BlackCard alloc]initFromText:@"Soup that is too hot."],
[[BlackCard alloc]initFromText:@"Muhammad (Praise Be Unto Him)."],
[[BlackCard alloc]initFromText:@"Surprise sex!"],
[[BlackCard alloc]initFromText:@"Five-Dollar Footlongs™."],
[[BlackCard alloc]initFromText:@"Drinking alone."],
[[BlackCard alloc]initFromText:@"Dick fingers."],
[[BlackCard alloc]initFromText:@"Multiple stab wounds."],
[[BlackCard alloc]initFromText:@"Soiling oneself."],
[[BlackCard alloc]initFromText:@"Child abuse."],
[[BlackCard alloc]initFromText:@"Anal beads."],
[[BlackCard alloc]initFromText:@"Civilian casualties."],
[[BlackCard alloc]initFromText:@"Pulling out."],
[[BlackCard alloc]initFromText:@"Robert Downey, Jr."],
[[BlackCard alloc]initFromText:@"Horse meat."],
[[BlackCard alloc]initFromText:@"A really cool hat."],
[[BlackCard alloc]initFromText:@"Kim Jong-il."],
[[BlackCard alloc]initFromText:@"A stray pube."],
[[BlackCard alloc]initFromText:@"Jewish fraternities."],
[[BlackCard alloc]initFromText:@"The token minority."],
[[BlackCard alloc]initFromText:@"Doin' it in the butt."],
[[BlackCard alloc]initFromText:@"Feeding Rosie O'Donnell."],
[[BlackCard alloc]initFromText:@"Teaching a robot to love."],
[[BlackCard alloc]initFromText:@"A can of whoop-ass."],
[[BlackCard alloc]initFromText:@"A windmill full of corpses."],
[[BlackCard alloc]initFromText:@"Count Chocula."],
[[BlackCard alloc]initFromText:@"Wearing underwear inside-out to avoid doing laundry."],
[[BlackCard alloc]initFromText:@"A death ray."],
[[BlackCard alloc]initFromText:@"The glass ceiling."],
[[BlackCard alloc]initFromText:@"A cooler full of organs."],
[[BlackCard alloc]initFromText:@"The American Dream."],
[[BlackCard alloc]initFromText:@"Keg stands."],
[[BlackCard alloc]initFromText:@"When you fart and a little bit comes out."],
[[BlackCard alloc]initFromText:@"Take-backsies."],
[[BlackCard alloc]initFromText:@"Dead babies."],
[[BlackCard alloc]initFromText:@"Foreskin."],
[[BlackCard alloc]initFromText:@"Saxophone solos."],
[[BlackCard alloc]initFromText:@"Italians."],
[[BlackCard alloc]initFromText:@"A fetus."],
[[BlackCard alloc]initFromText:@"Firing a rifle into the air while balls deep in a squealing hog."],
[[BlackCard alloc]initFromText:@"Dick Cheney."],
[[BlackCard alloc]initFromText:@"Amputees."],
[[BlackCard alloc]initFromText:@"Eugenics."],
[[BlackCard alloc]initFromText:@"My relationship status."],
[[BlackCard alloc]initFromText:@"Christopher Walken."],
[[BlackCard alloc]initFromText:@"Bees?"],
[[BlackCard alloc]initFromText:@"Harry Potter erotica."],
[[BlackCard alloc]initFromText:@"College."],
[[BlackCard alloc]initFromText:@"Getting drunk on mouthwash."],
[[BlackCard alloc]initFromText:@"Nazis."],
[[BlackCard alloc]initFromText:@"8 oz. of sweet Mexican black-tar heroin."],
[[BlackCard alloc]initFromText:@"Stephen Hawking talking dirty."],
[[BlackCard alloc]initFromText:@"Dead parents."],
[[BlackCard alloc]initFromText:@"Object permanence."],
[[BlackCard alloc]initFromText:@"Opposable thumbs."],
[[BlackCard alloc]initFromText:@"Racially-biased SAT questions."],
[[BlackCard alloc]initFromText:@"Jibber-jabber."],
[[BlackCard alloc]initFromText:@"Chainsaws for hands."],
[[BlackCard alloc]initFromText:@"Nicolas Cage."],
[[BlackCard alloc]initFromText:@"Child beauty pageants."],
[[BlackCard alloc]initFromText:@"Explosions."],
[[BlackCard alloc]initFromText:@"Sniffing glue."],
[[BlackCard alloc]initFromText:@"Glenn Beck being harried by a swarm of buzzards."],
[[BlackCard alloc]initFromText:@"Repression."],
[[BlackCard alloc]initFromText:@"Roofies."],
[[BlackCard alloc]initFromText:@"My vagina."],
[[BlackCard alloc]initFromText:@"Assless chaps."],
[[BlackCard alloc]initFromText:@"A murder most foul."],
[[BlackCard alloc]initFromText:@"Giving 110 percent."],
[[BlackCard alloc]initFromText:@"Her Royal Highness, Queen Elizabeth II."],
[[BlackCard alloc]initFromText:@"The Trail of Tears."],
[[BlackCard alloc]initFromText:@"Being marginalized."],
[[BlackCard alloc]initFromText:@"Goblins."],
[[BlackCard alloc]initFromText:@"Hope."],
[[BlackCard alloc]initFromText:@"The Rev. Dr. Martin Luther King, Jr."],
[[BlackCard alloc]initFromText:@"A micropenis."],
[[BlackCard alloc]initFromText:@"My soul."],
[[BlackCard alloc]initFromText:@"A hot mess."],
[[BlackCard alloc]initFromText:@"Vikings."],
[[BlackCard alloc]initFromText:@"Hot people."],
[[BlackCard alloc]initFromText:@"Seduction."],
[[BlackCard alloc]initFromText:@"An Oedipus complex."],
[[BlackCard alloc]initFromText:@"Geese."],
[[BlackCard alloc]initFromText:@"Global warming."],
[[BlackCard alloc]initFromText:@"New Age music."],
[[BlackCard alloc]initFromText:@"Hot Pockets."],
[[BlackCard alloc]initFromText:@"Making a pouty face."],
[[BlackCard alloc]initFromText:@"Vehicular manslaughter."],
[[BlackCard alloc]initFromText:@"Women's suffrage."],
[[BlackCard alloc]initFromText:@"A defective condom."],
[[BlackCard alloc]initFromText:@"Judge Judy."],
[[BlackCard alloc]initFromText:@"African children."],
[[BlackCard alloc]initFromText:@"The Virginia Tech Massacre."],
[[BlackCard alloc]initFromText:@"Barack Obama."],
[[BlackCard alloc]initFromText:@"Asians who aren't good at math."],
[[BlackCard alloc]initFromText:@"Elderly Japanese men."],
[[BlackCard alloc]initFromText:@"Exchanging pleasantries."],
[[BlackCard alloc]initFromText:@"Heteronormativity."],
[[BlackCard alloc]initFromText:@"Parting the Red Sea."],
[[BlackCard alloc]initFromText:@"Arnold Schwarzenegger."],
[[BlackCard alloc]initFromText:@"Road head."],
[[BlackCard alloc]initFromText:@"Spectacular abs."],
[[BlackCard alloc]initFromText:@"Figgy pudding."],
[[BlackCard alloc]initFromText:@"A mopey zoo lion."],
[[BlackCard alloc]initFromText:@"A bag of magic beans."],
[[BlackCard alloc]initFromText:@"Poor life choices."],
[[BlackCard alloc]initFromText:@"My sex life."],
[[BlackCard alloc]initFromText:@"Auschwitz."],
[[BlackCard alloc]initFromText:@"A snapping turtle biting the tip of your penis."],
[[BlackCard alloc]initFromText:@"A thermonuclear detonation."],
[[BlackCard alloc]initFromText:@"The clitoris."],
[[BlackCard alloc]initFromText:@"The Big Bang."],
[[BlackCard alloc]initFromText:@"Land mines."],
[[BlackCard alloc]initFromText:@"Friends who eat all the snacks."],
[[BlackCard alloc]initFromText:@"Goats eating cans."],
[[BlackCard alloc]initFromText:@"The Dance of the Sugar Plum Fairy."],
[[BlackCard alloc]initFromText:@"Jerking off into a pool of children's tears."],
[[BlackCard alloc]initFromText:@"Man meat."],
[[BlackCard alloc]initFromText:@"Me time."],
[[BlackCard alloc]initFromText:@"The Underground Railroad."],
[[BlackCard alloc]initFromText:@"Poorly-timed Holocaust jokes."],
[[BlackCard alloc]initFromText:@"A sea of troubles."],
[[BlackCard alloc]initFromText:@"Lumberjack fantasies."],
[[BlackCard alloc]initFromText:@"Morgan Freeman's voice."],
[[BlackCard alloc]initFromText:@"Women in yogurt commercials."],
[[BlackCard alloc]initFromText:@"Natural male enhancement."],
[[BlackCard alloc]initFromText:@"Being a motherfucking sorcerer."],
[[BlackCard alloc]initFromText:@"Genital piercings."],
[[BlackCard alloc]initFromText:@"Passable transvestites."],
[[BlackCard alloc]initFromText:@"Sexy pillow fights."],
[[BlackCard alloc]initFromText:@"Balls."],
[[BlackCard alloc]initFromText:@"Grandma."],
[[BlackCard alloc]initFromText:@"Friction."],
[[BlackCard alloc]initFromText:@"Party poopers."],
[[BlackCard alloc]initFromText:@"Farting and walking away."],
[[BlackCard alloc]initFromText:@"Being a dick to children."],
[[BlackCard alloc]initFromText:@"Booby-trapping the house to foil burglars."],
[[BlackCard alloc]initFromText:@"The Tempur-Pedic Swedish Sleep System™."],
[[BlackCard alloc]initFromText:@"Dying."],
[[BlackCard alloc]initFromText:@"Hurricane Katrina."],
[[BlackCard alloc]initFromText:@"The gays."],
[[BlackCard alloc]initFromText:@"The folly of man."],
[[BlackCard alloc]initFromText:@"Men."],
[[BlackCard alloc]initFromText:@"The Amish."],
[[BlackCard alloc]initFromText:@"Pterodactyl eggs."],
[[BlackCard alloc]initFromText:@"Team-building exercises."],
[[BlackCard alloc]initFromText:@"A brain tumor."],
[[BlackCard alloc]initFromText:@"Cards Against Humanity."],
[[BlackCard alloc]initFromText:@"Fear itself."],
[[BlackCard alloc]initFromText:@"Lady Gaga."],
[[BlackCard alloc]initFromText:@"The milk man."],
[[BlackCard alloc]initFromText:@"A foul mouth."],
[[BlackCard alloc]initFromText:@"A big black dick."],
[[BlackCard alloc]initFromText:@"A beached whale."],
[[BlackCard alloc]initFromText:@"A bloody pacifier."],
[[BlackCard alloc]initFromText:@"A crappy little hand."],
[[BlackCard alloc]initFromText:@"A low standard of living."],
[[BlackCard alloc]initFromText:@"A nuanced critique."],
[[BlackCard alloc]initFromText:@"Panty raids."],
[[BlackCard alloc]initFromText:@"A passionate Latino lover."],
[[BlackCard alloc]initFromText:@"A rival dojo."],
[[BlackCard alloc]initFromText:@"A web of lies."],
[[BlackCard alloc]initFromText:@"A woman scorned."],
[[BlackCard alloc]initFromText:@"Clams."],
[[BlackCard alloc]initFromText:@"Apologizing."],
[[BlackCard alloc]initFromText:@"Appreciative snapping."],
[[BlackCard alloc]initFromText:@"Neil Patrick Harris."],
[[BlackCard alloc]initFromText:@"Beating your wives."],
[[BlackCard alloc]initFromText:@"Being a dinosaur."],
[[BlackCard alloc]initFromText:@"Shaft."],
[[BlackCard alloc]initFromText:@"Bosnian chicken farmers."],
[[BlackCard alloc]initFromText:@"Nubile slave boys."],
[[BlackCard alloc]initFromText:@"Carnies."],
[[BlackCard alloc]initFromText:@"Coughing into a vagina."],
[[BlackCard alloc]initFromText:@"Suicidal thoughts."],
[[BlackCard alloc]initFromText:@"Dancing with a broom."],
[[BlackCard alloc]initFromText:@"Deflowering the princess."],
[[BlackCard alloc]initFromText:@"Dorito breath."],
[[BlackCard alloc]initFromText:@"Eating an albino."],
[[BlackCard alloc]initFromText:@"Enormous Scandinavian women."],
[[BlackCard alloc]initFromText:@"Fabricating statistics."],
[[BlackCard alloc]initFromText:@"Finding a skeleton."],
[[BlackCard alloc]initFromText:@"Gandalf."],
[[BlackCard alloc]initFromText:@"Genetically engineered super-soldiers."],
[[BlackCard alloc]initFromText:@"George Clooney's musk."],
[[BlackCard alloc]initFromText:@"Getting abducted by Peter Pan."],
[[BlackCard alloc]initFromText:@"Getting in her pants, politely."],
[[BlackCard alloc]initFromText:@"Gladiatorial combat."],
[[BlackCard alloc]initFromText:@"Good grammar."],
[[BlackCard alloc]initFromText:@"Hipsters."],
[[BlackCard alloc]initFromText:@"Historical revisionism."],
[[BlackCard alloc]initFromText:@"Insatiable bloodlust."],
[[BlackCard alloc]initFromText:@"Jafar."],
[[BlackCard alloc]initFromText:@"Jean-Claude Van Damme."],
[[BlackCard alloc]initFromText:@"Just the tip."],
[[BlackCard alloc]initFromText:@"Mad hacky-sack skills."],
[[BlackCard alloc]initFromText:@"Leveling up."],
[[BlackCard alloc]initFromText:@"Literally eating shit."],
[[BlackCard alloc]initFromText:@"Making the penises kiss."],
[[BlackCard alloc]initFromText:@"Media coverage."],
[[BlackCard alloc]initFromText:@"Medieval Times Dinner and Tournament."],
[[BlackCard alloc]initFromText:@"Moral ambiguity."],
[[BlackCard alloc]initFromText:@"My machete."],
[[BlackCard alloc]initFromText:@"One thousand Slim Jims."],
[[BlackCard alloc]initFromText:@"Ominous background music."],
[[BlackCard alloc]initFromText:@"Overpowering your father."],
[[BlackCard alloc]initFromText:@"Pistol-whipping a hostage."],
[[BlackCard alloc]initFromText:@"Quiche."],
[[BlackCard alloc]initFromText:@"Quivering jowls."],
[[BlackCard alloc]initFromText:@"Revenge fucking."],
[[BlackCard alloc]initFromText:@"Ripping into a man's chest and pulling out his still-beating heart."],
[[BlackCard alloc]initFromText:@"Ryan Gosling riding in on a white horse."],
[[BlackCard alloc]initFromText:@"Santa Claus."],
[[BlackCard alloc]initFromText:@"Scrotum tickling."],
[[BlackCard alloc]initFromText:@"Sexual humiliation."],
[[BlackCard alloc]initFromText:@"Sexy Siamese twins."],
[[BlackCard alloc]initFromText:@"Slow motion."],
[[BlackCard alloc]initFromText:@"Space muffins."],
[[BlackCard alloc]initFromText:@"Statistically validated stereotypes."],
[[BlackCard alloc]initFromText:@"Sudden Poop Explosion Disease."],
[[BlackCard alloc]initFromText:@"The boners of the elderly."],
[[BlackCard alloc]initFromText:@"The economy."],
[[BlackCard alloc]initFromText:@"The Fanta girls."],
[[BlackCard alloc]initFromText:@"The Gulags."],
[[BlackCard alloc]initFromText:@"The harsh light of day."],
[[BlackCard alloc]initFromText:@"The hiccups."],
[[BlackCard alloc]initFromText:@"The shambling corpse of Larry King."],
[[BlackCard alloc]initFromText:@"The four arms of Vishnu."],
[[BlackCard alloc]initFromText:@"Being a busy adult with many important things to do."],
[[BlackCard alloc]initFromText:@"Tripping balls."],
[[BlackCard alloc]initFromText:@"Words, words, words."],
[[BlackCard alloc]initFromText:@"Zeus's sexual appetites."], nil];
    
    return blackCards;
}

+(NSArray*)getWhiteCards{
    NSArray* whiteCards = [[NSMutableArray alloc]initWithObjects:
                           [[WhiteCard alloc]initFromText:@"TSA guidelines now prohibit __________ on airplanes." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"It's a pity that kids these days are all getting involved with __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In 1,000 years, when paper money is but a distant memory, __________ will be our currency." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Major League Baseball has banned __________ for giving players an unfair advantage." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What is Batman's guilty pleasure?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Next from J.K. Rowling: Harry Potter and the Chamber of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"I'm sorry, Professor, but I couldn't complete my homework because of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What did I bring back from Mexico?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________? There's an app for that." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________. Betcha can't have just one!" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's my anti-drug?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time. " andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's my secret power?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's the new fad diet?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What did Vin Diesel eat for dinner?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"When Pharaoh remained unmoved, Moses called down a Plague of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"How am I maintaining my relationship status?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's the crustiest?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In L.A. County Jail, word is you can trade 200 cigarettes for __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"After the earthquake, Sean Penn brought __________ to the people of Haiti." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Instead of coal, Santa now gives the bad children __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Life for American Indians was forever changed when the White Man introduced them to __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's Teach for America using to inspire inner city students to succeed?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Maybe she's born with it. Maybe it's __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In Michael Jackson's final moments, he thought about __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"White people like __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Why do I hurt all over?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"A romantic, candlelit dinner would be incomplete without __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What will I bring back in time to convince people that I am a powerful wizard?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"BILLY MAYS HERE FOR __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"The class field trip was completely ruined by __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's a girl's best friend?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Dear Abby, I'm having some trouble with __________ and would like your advice." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"When I am President of the United States, I will create the Department of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What are my parents hiding from me?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What never fails to liven up the party?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What gets better with age?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________: Good to the last drop." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"I got 99 problems but __________ ain't one." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________. It's a trap!" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"MTV's new reality show features eight washed-up celebrities living with __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What would grandma find disturbing, yet oddly charming?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's the most emo?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"During sex, I like to think about __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What ended my last relationship?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's that sound?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________. That's how I want to die." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Why am I sticky?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's the next Happy Meal toy?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's there a ton of in heaven?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"I do not know with what weapons World War III will be fought, but World War IV will be fought with __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What will always get you laid?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________: Kid-tested, mother-approved." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Why can't I sleep at night?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's that smell?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What helps Obama unwind?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"This is the way the world ends / This is the way the world ends / Not with a bang but with __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Coming to Broadway this season, __________: The Musical." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Anthropologists have recently discovered a primitive tribe that worships __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"But before I kill you, Mr. Bond, I must show you __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Studies show that lab rats navigate mazes 50% faster after being exposed to __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Next on ESPN2: The World Series of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"When I am a billionaire, I shall erect a 50-foot statue to commemorate __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"War! What is it good for?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What gives me uncontrollable gas?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What do old people smell like?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What am I giving up for Lent?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Alternative medicine is now embracing the curative powers of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What did the US airdrop to the children of Afghanistan?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What does Dick Cheney prefer?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What don't you want to find in your Chinese food?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"I drink to forget __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"__________. High five, bro." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"He who controls __________ controls the world." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"The CIA now interrogates enemy agents by repeatedly subjecting them to __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In Rome, there are whisperings that the Vatican has a secret room devoted to __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"Science will never explain the origin of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"When all else fails, I can always masturbate to __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"I learned the hard way that you can't cheer up a grieving friend with __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"The socialist governments of Scandinavia have declared that access to __________ is a basic human right." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In his new self-produced album, Kanye West raps over the sounds of __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What's the gift that keeps on giving?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __________ and his wits. " andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"When I pooped, what came out of my butt?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"In the distant future, historians will agree that __________ marked the beginning of America's decline." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What has been making life difficult at the nudist colony?" andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"And I would have gotten away with it, too, if it hadn't been for __________." andNdOfBlackCard:1],
                           [[WhiteCard alloc]initFromText:@"What brought the orgy to a grinding halt?" andNdOfBlackCard:1],
                           
                           [[WhiteCard alloc]initFromText:@"__________. High five, bro." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"TSA guidelines now prohibit __________ on airplanes." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"It's a pity that kids these days are all getting involved with __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In 1,000 years, when paper money is but a distant memory, __________ will be our currency." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Major League Baseball has banned __________ for giving players an unfair advantage." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What is Batman's guilty pleasure?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Next from J.K. Rowling: Harry Potter and the Chamber of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I'm sorry, Professor, but I couldn't complete my homework because of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What did I bring back from Mexico?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"__________? There's an app for that." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Betcha can't have just one!" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's my anti-drug?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's my secret power?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's the new fad diet?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What did Vin Diesel eat for dinner?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"When Pharaoh remained unmoved, Moses called down a Plague of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"How am I maintaining my relationship status?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's the crustiest?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"When I'm in prison, I'll have __________ smuggled in." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Instead of coal, Santa now gives the bad children __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Life was difficult for cavemen before __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's Teach for America using to inspire inner city students to succeed?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Who stole the cookies from the cookie jar?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In Michael Jackson's final moments, he thought about __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"White people like __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Why do I hurt all over?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"A romantic candlelit dinner would be incomplete without __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What will I bring back in time to convince people that I am a powerful wizard?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"BILLY MAYS HERE FOR __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"The class field trip was completely ruined by __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's a girl's best friend?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I wish I hadn't lost the instruction manual for __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"When I am President of the United States, I will create the Department of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What are my parents hiding from me?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What never fails to liven up the party?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What gets better with age?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"__________: good to the last drop." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I got 99 problems but __________ ain't one." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"It's a trap!" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"MTV's new reality show features eight washed-up celebrities living with __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What would grandma find disturbing, yet oddly charming?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's the most emo?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"During sex, I like to think about __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What ended my last relationship?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's that sound?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"__________. That's how I want to die." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Why am I sticky?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's the next Happy MealÂ® toy?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's there a ton of in heaven?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I do not know with what weapons World War III will be fought, but World War IV will be fought with __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What will always get you laid?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"__________: kid tested, mother approved." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Why can't I sleep at night?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's that smell?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What helps Obama unwind?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"This is the way the world ends. Not with a bang but with __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Coming to Broadway this season, __________: The Musical." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Anthropologists have recently discovered a primitive tribe that worships __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"But before I kill you, Mr. Bond, I must show you __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Studies show that lab rats navigate mazes 50% faster after being exposed to __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Due to a PR fiasco, Walmart no longer offers __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"When I am a billionaire, I shall erect a 50-foot statue to commemorate __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"War! What is it good for?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What gives me uncontrollable gas?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What do old people smell like?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Sorry everyone, I just __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Alternative medicine is now embracing the curative powers of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"The U.S. has begun airdropping __________ to the children of Afghanistan." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What does Dick Cheney prefer?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What don't you want to find in your Chinese food?" andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I drink to forget __________."andNdOfBlackCard:1],
                        [[WhiteCard alloc]initFromText:@"That's right, I killed __________. How, you ask? __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"And the Academy Award for __________ goes to __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"For my next trick, I will pull __________ out of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In his new summer comedy, Rob Schneider is __________ trapped in the body of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"When I was tripping on acid, __________ turned into __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"__________ is a slippery slope that leads to __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In a world ravaged by __________, our only solace is __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"In M. Night Shyamalan's new movie, Bruce Willis discovers that __________ had really been __________ all along." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"I never truly understood __________ until I encountered __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"Rumor has it that Vladimir Putin's favorite dish is __________ stuffed with __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"LifetimeÂ® presents __________, the story of __________." andNdOfBlackCard:1],
[[WhiteCard alloc]initFromText:@"What's the next superhero/sidekick duo?"andNdOfBlackCard:1], nil];

    
    return whiteCards;
}
@end
